"""books table

Revision ID: 07dc0448d6c6
Revises: 9256c9c3afd7
Create Date: 2022-01-23 17:15:26.195246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07dc0448d6c6'
down_revision = '9256c9c3afd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('author', sa.String(length=120), nullable=True),
    sa.Column('genre', sa.String(length=120), nullable=True),
    sa.Column('publish_date', sa.Date(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('complete_date', sa.Date(), nullable=True),
    sa.Column('tags', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_complete_date'), 'book', ['complete_date'], unique=False)
    op.create_index(op.f('ix_book_publish_date'), 'book', ['publish_date'], unique=False)
    op.create_index(op.f('ix_book_rating'), 'book', ['rating'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_rating'), table_name='book')
    op.drop_index(op.f('ix_book_publish_date'), table_name='book')
    op.drop_index(op.f('ix_book_complete_date'), table_name='book')
    op.drop_table('book')
    # ### end Alembic commands ###
