"""users table

Revision ID: b17437155b26
Revises: 
Create Date: 2022-02-21 13:47:21.014298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b17437155b26'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('author', sa.String(length=120), nullable=True),
    sa.Column('genre', sa.String(length=120), nullable=True),
    sa.Column('publish_date', sa.Date(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('complete_date', sa.Date(), nullable=True),
    sa.Column('tags', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_complete_date'), 'book', ['complete_date'], unique=False)
    op.create_index(op.f('ix_book_publish_date'), 'book', ['publish_date'], unique=False)
    op.create_index(op.f('ix_book_rating'), 'book', ['rating'], unique=False)
    op.create_table('screen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('genre', sa.String(length=120), nullable=True),
    sa.Column('director', sa.String(length=120), nullable=True),
    sa.Column('watched', sa.Boolean(), nullable=True),
    sa.Column('my_rating', sa.Integer(), nullable=True),
    sa.Column('rt_rating', sa.Integer(), nullable=True),
    sa.Column('watched_date', sa.Date(), nullable=True),
    sa.Column('tags', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('screen')
    op.drop_index(op.f('ix_book_rating'), table_name='book')
    op.drop_index(op.f('ix_book_publish_date'), table_name='book')
    op.drop_index(op.f('ix_book_complete_date'), table_name='book')
    op.drop_table('book')
    # ### end Alembic commands ###
